version: '3'
services:
  db:
    container_name: data_base
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
  
  migrator:  
    container_name: data_base_migrator  
    image: postgres_db
    environment:
      - POSTGRES_PASSWORD=postgres
    command: >
      bash -c "su - postgres && 
               PGPASSWORD=postgres psql --host=db --port=5432 --username=postgres --file /opt/acesso_init.sql"
    depends_on:
      - db
  
  application:
    container_name: java_application
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        USERNAME: "postgres"
        PASSWORD: "postgres"
        DATASOURCE_URL: "jdbc:postgresql://db:5432/postgres"
    ports:
      - "9094:9095"
    depends_on:
      - db
  
