version: '3'
services:
  db:
    container_name: data_base
    image: postgres_db
    environment:
      - POSTGRES_PASSWORD=postgres       
  
  application:
    container_name: java_application
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 5432
        DATASOURCE_USERNAME: postgres
        DATASOURCE_PASSWORD: postgres
        HOST: db
        DBNAME: postgres
    ports:
      - "9094:9095"
    links:
      - db
  
