version: '3'
services:
  db:
    container_name: data_base
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"
    networks:
      - new
  
  application:
    container_name: java_application
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        USERNAME: "postgres"
        PASSWORD: "postgres"
        DATASOURCE_URL: "jdbc:postgresql://db:5432/postgres"
    ports:
      - "9094:9095"
    depends_on:
      - db
    networks:
      - new  

networks:
  new:
  
