node() { 
    stage 'Stop data base'
        sh 'docker stop data_base'
        sh 'docker rm data_base'

     stage 'Stop java application'
        sh 'docker stop java_application'
        sh 'docker rm java_application'
}